name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed
  push:
    branches:
      - '**'
    paths:
      - 'k8s/**'
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/ -R

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/user-service --timeout=300s

      - name: Dynamic Application Security Testing (DAST) 🛡️
        run: |
          echo "Starting DAST on deployed application..."
          SERVICE_IP=$(kubectl get svc user-service -o jsonpath='{.spec.clusterIP}')
          curl -f http://$SERVICE_IP:5000/healthz || echo "Health check failed"
          if [ $? -eq 0 ]; then echo "✅ DAST health check passed"; else echo "⚠️ DAST health check failed"; fi
          echo "✅ DAST completed on live application"